// START SCREEN => title , start , small 'coded by'
const body = document.querySelector("body");

// //! translate to html start screen
// //* Title
// const titleCard = document.createElement("h1");
// titleCard.innerText = "HANGMAN";
// titleCard.classList.add("heading");

// console.log(titleCard);

// body.appendChild(titleCard);

// //* Start Button
// const startBtn = document.createElement("button");
// startBtn.innerText = "S T A R T";

// console.log(startBtn);
// body.appendChild(startBtn);

// //* 'Coded By'
// const codedBy = document.createElement("small");
// codedBy.innerText = "coded by heisenburs";

// console.log(codedBy);
// body.appendChild(codedBy);
// - Click on start button => Brings you to play screen

// 3 Category [button]
const codingCategory = document.querySelector(".codingCategory");
// codingCategory.innerText = "CODING";

console.log(codingCategory);
body.appendChild(codingCategory);

const moviesCategory = document.querySelector(".moviesCategory");
// moviesCategory.innerText = "MOVIES";

console.log(moviesCategory);
body.appendChild(moviesCategory);

const locationCategory = document.querySelector(".locationCategory");
// locationCategory.innerText = "LOCATIONS";

console.log(locationCategory);
body.appendChild(locationCategory);

// Random choice generated by Category button
//stays
codingCategory.addEventListener("click", () => {
  //when you click, let a random word appear
  let codingKey =
    codingChoices[Math.floor(Math.random() * codingChoices.length)];

  // the randomly generated word goes into the <p> tag
  let codKey = document.querySelector(".keyword");

  let codingArr = [];

  // loops through created array
  for (let i = 0; i < codingKey.length; i++) {
    // create span element
    let span = document.createElement("span");
    span.textContent = "_";
    codKey.appendChild(span);
    // adds "_" to the new array
    codingArr.push(" _ ");
  }

  console.log(codingKey);
  console.log(codingArr);
  codKey.innerText = codingArr;
});

moviesCategory.addEventListener("click", () => {
  let movieKey = movieChoices[Math.floor(Math.random() * movieChoices.length)];

  let movKey = document.querySelector(".keyword");
  let movieArr = [];

  for (let i = 0; i < movieKey.length; i++) {
    let span = document.createElement("span");
    span.textContent = "_";
    movKey.appendChild(span);
    movieArr.push(" _ ");
  }

  console.log(movieKey);
  console.log(movieArr);
  movKey.innerText = movieArr;
});

locationCategory.addEventListener("click", () => {
  let locationKey =
    locationChoices[Math.floor(Math.random() * locationChoices.length)];

  let locKey = document.querySelector(".keyword");
  let locationArr = [];

  for (let i = 0; i < locationKey.length; i++) {
    let span = document.createElement("span");
    span.textContent = "_";
    locKey.appendChild(span);
    locationArr.push(" _ ");
  }

  console.log(locationKey);
  console.log(locationArr);
  locKey.innerText = locationArr;
});

// Coding => JAVASCRIPT , REACT , MERN STACK

let codingChoices = ["Javascript", "React", "MERN Stack"];

// Movies => MULAN , NEW JACK CITY , TWILIGHT
let movieChoices = ["Mulan", "New Jack City", "Twilight"];

// Locations => AMSTERDAM , BOSTON , COSTA RICA
let locationChoices = ["Amsterdam", "Boston", "Costa Rica"];

console.log(codingChoices);
console.log(movieChoices);
console.log(locationChoices);

// Alphabet at the bottom

let letterChoices = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

for (let letter of letterChoices) {
  //create an element (p or button)
  let btn = document.createElement("button");
  // set value of buttons to their value in the array
  btn.innerText = letter;
  // append letters to letter-body
  body.append(btn);
  btn.classList.add("btn");

  btn.onclick = () => {
    console.log(btn.innerText);
  };
}
// function check() {
//   for (let i = 0; i < letterChoices.length; i++) {
//     for (let j = 0; j < i.length; j++) {
//       if (char === j) {
//         console.log(char);
//       }
//     }
//   }
// }
//gets buttons to log their value

//
//   btn.addEventListener("click", () => {
//     btn.check();
//   });

//create function
//includes()
//.indexOf()

// addEventListener("click", () => {

// })

// Have the letters of the keyword show, but hidden => if the correct letter is pressed, the letter in the keyword will show

// if the incorrect letter is pressed, a piece of the hangman will appear

// If you click on a letter => it will check to see if it fills a blank
// After you click the letter, it is hidden
// If it does, the letter will fill the blank
// If not, a piece of the hangman will appear

// Repeats until all blanks are filled
// If all blanks are filled before man is completely hanged
// Alert: You have won!
// All pieces of the hanged man have appeared
//-- If the man is completely hanged before all blanks are filled
// Alert: LOSER!
// (Tony todd laugh?)

const hangmanArr = [];

const head = document.querySelector(".hangman-head");

hangmanArr.push(head);

const stickbody = document.querySelector(".hangman-body");

hangmanArr.push(stickbody);

const leftarm = document.querySelector(".hangman-left-arm");

hangmanArr.push(leftarm);

const rightarm = document.querySelector(".hangman-right-arm");

hangmanArr.push(rightarm);

const leftleg = document.querySelector(".hangman-left-leg");

hangmanArr.push(leftleg);

const rightleg = document.querySelector(".hangman-right-leg");

hangmanArr.push(rightleg);

const leftfoot = document.querySelector(".hangman-left-foot");

hangmanArr.push(leftfoot);

const rightfoot = document.querySelector(".hangman-right-foot");

hangmanArr.push(rightfoot);

console.log(hangmanArr);

for (let piece of hangmanArr) {
  piece.hidden = true;
}

//click button => loop through each letter and check to see if the value of the button matches the letter that is being checked => if it matches, it will fill in, if it doesnt match, a piece of the stick figure will show (loop through pieces array?)

// function check(char) {
//   btn.addEventListener("click", () => {
//     btn.check();
//   });

//   for (let i = 0; i < locKey.length; i++) {
//     for (let j = 0; j < i.length; j++) {
//       if (char === j) {
//         console.log(char);
//       }
//     }
//   }
// }

// function listenForMatch(char) {btn.addEventListener("click", () => {
//     console.log(btn.listenForMatch());
//   for (let i = 0; i < locationArr.length; i++) {
//     // for loop grapbs each letter in the selected word
//     for (let j = 0; j < i.length; j++) {
//       if (char === j) {
//         i[j] = char;
//       }
//     }}
//   });

//Ashleys Hangman Code
// //function to remove flowers only if the letter is incorrect
//function handleClick(e) {

//* letter if not found remove a flower
//if(amountOfChances<1){
//    confirm("Oh no! You Lose!")
//}else{

//   if (mysteryWord.toUpperCase().includes(e.target.innerHTML) == true) {
//Update the Array to change letter from underscore

//    } else {
//        let flowers = document.querySelectorAll('.littleflower')
//        amountOfChances-=1
//        flowers[flowers.length - 1].remove()
//
//        console.log(flowers)
//        console.log(flowers.length)
//        console.log(amountOfChances)
//    }
//}
//
